name: Framework

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'src/**'
      - 'package.json'
      - 'yarn.lock'
      - '.yarnrc.yml'
      - '.github/workflows/**'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'src/**'
      - 'package.json'
      - 'yarn.lock'
      - '.yarnrc.yml'
      - '.github/workflows/**'

jobs:
  framework:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
          restore-keys: |
            yarn-cache-folder-

      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Typecheck
        run: |
          yarn typecheck

      - name: Linter
        run: |
          yarn lint --cache

      - name: Unit tests
        run: |
          echo 1

      - name: Build
        run: |
          yarn build

      - name: Check bundle size
        run: |
          yarn check-size
